name: Docker Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Building docker
        run: docker-compose build
      - name: Running cluster testing
        run: src/testing/docker/test-cluster.sh
      - name: Running standalone testing
        run: src/testing/docker/test-standalone.sh
